# Generated by Django 5.0.6 on 2024-06-11 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='roleJobTitles',
            new_name='roleJobTitle',
        ),
        migrations.RemoveField(
            model_name='project',
            name='crew_requirements',
        ),
        migrations.RemoveField(
            model_name='project',
            name='selected_crews',
        ),
        migrations.CreateModel(
            name='CrewRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('number_needed', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_requirements_set', to='crew.project')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.crewmember')),
                ('crew_requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.crewrequirement')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_crews_set', to='crew.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='crew_requirements',
            field=models.ManyToManyField(related_name='projects_set', to='crew.crewrequirement'),
        ),
        migrations.AddField(
            model_name='project',
            name='selected_crews',
            field=models.ManyToManyField(related_name='projects_set', to='crew.selectedcrew'),
        ),
    ]
