# Generated by Django 5.0.6 on 2024-06-11 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0002_rename_rolejobtitles_project_rolejobtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='queries',
        ),
        migrations.RemoveField(
            model_name='project',
            name='roleJobTitle',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
